POST http://localhost:3000/user-written-blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzUyZmUzZjhiMjlkNjNkNjdkMmM3OCIsImlhdCI6MTc1MTQ4NTUyM30.9tFdimfKTBGpcFq7Pc03IJMn4pFD7ECGjQhyM3iWMPM

{
  "page": 1,
  "draft": true
}

